import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

//Alterar a descrição conforme o cliente
export const metadata: Metadata = {
  title: "GMD - Logística",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${montserrat.variable}`}>
      <body className={`${montserrat.variable}`}>{children}</body>
    </html>
  );
}